inventories:
  filler:
    enabled: true
    item: STAINED_GLASS_PANE
    color: BLACK

shops:
  main:
    title: "&c&lShopX &f- Main Shop"
    size: 36
    inventory:
      10:
        item: DIAMOND
        name: "&bResources"